### ISSUE TITLE
Currency GBP Please

### ISSUE THREAD

**Issue by Tiiiiiix** [Loopring/loopring-wallet-feedback#127] opened 2021-12-22 15:44 UTC
Please add GBP for true accessibility

**Comment by a-triant** [comment] 2021-12-22 17:38
Duplicate of #114

**Comment by a-triant** [comment] 2021-12-22 17:40
Duplicate of #114

**Comment by odesium** [comment] 2022-01-11 11:52
Duplicate o f #114

**Closed by odesium** 2022-01-11 11:52 UTC
