### ISSUE TITLE
Mobile wallet support for display of NFTs minted with CIDv1

### ISSUE THREAD

**Issue by brachsterX** [Loopring/loopring-wallet-feedback#206] opened 2022-05-07 18:00 UTC
Currently, the mobile wallet supports only NFTs minted with CIDv0 hash

That would mean CIDs with initials `Qm`

CIDv1 hash has a starting initial of `bafy` and NFTs minted with this kind of hash results in an Unknown NFT in the wallet.

![image](https://user-images.githubusercontent.com/97795503/167254887-76a20b7c-250c-4735-a420-675c048b7ef5.png)

Example metadata for an NFT with CIDv1 hash.

![image](https://user-images.githubusercontent.com/97795503/167285318-c11d1837-d9d8-4936-829e-6e55f74350ee.png)

This issue is noted in iOS, latest version 2.0.23.

**Comment by Jye924** [comment] 2022-05-08 12:11
Would you send your wallet address to us? Thank you

**Comment by brachsterX** [comment] 2022-05-08 19:55
Hi, this is the affected wallet. 

0x292224bd033fc6621bade232934a87a1f66884ef

**Comment by Jye924** [comment] 2022-05-09 03:04
Do you have transferred out all your NFTs?

**Comment by brachsterX** [comment] 2022-05-09 05:45
Hi Jye,

https://explorer.loopring.io/nft/0x1731aec6248c60836d288ae614898648d3f99afd-0-0xf131ba864ff15c6ba1e0eb29e5282dfc72411027-0x6c4f826ad4bcccf462f134342bdf1155e8cf5da0ac5382784b3ed828f04225e5-10

This NFT is still in the wallet and is not transferred out.

**Comment by ghost** [comment] 2022-05-09 12:31
@brachsterX @Jye924 I posted a related issue some time ago here: https://github.com/Loopring/loopring-wallet-feedback/issues/193

If this person uploaded metadata with a CIDv1, i'm not sure that this can be fixed. If they _only_ uploaded the image with CIDv1, then using the loopring Pinata gateway on mobile would be a blanket fix, as that functions perfectly on the explorer.

EDIT: looks like this person only used CIDv1 for the image, but the other bug/request is still pertinent as it can cause some truly broken NFTs to get created.

**Comment by Jye924** [comment] 2022-05-13 12:44
please 

> Hi Jye,
> 
> https://explorer.loopring.io/nft/0x1731aec6248c60836d288ae614898648d3f99afd-0-0xf131ba864ff15c6ba1e0eb29e5282dfc72411027-0x6c4f826ad4bcccf462f134342bdf1155e8cf5da0ac5382784b3ed828f04225e5-10
> 
> This NFT is still in the wallet and is not transferred out.

Please check your NFTs again.

**Comment by ghost** [comment] 2022-05-13 20:20
@Jye924 Is there an update needed to check this?  Is it only for iOS, or is there an Android fix as well?

I am unable to view my NFTs where the image has CIDv1 still in Android wallet or Web wallet at loopring.io.

**Comment by Jye924** [comment] 2022-05-14 01:35
> @Jye924 Is there an update needed to check this? Is it only for iOS, or is there an Android fix as well?
> 
> I am unable to view my NFTs where the image has CIDv1 still in Android wallet or Web wallet at loopring.io.

@sk33z3r  Please send your NFT id and token address to us, we will check in the backend.

**Comment by ghost** [comment] 2022-05-14 02:02
@Jye924 Thanks for being responsive. I have two that are affected at the moment.

### NFT 01

* nftID: `0xefa30533c25874d23f31e55be15aad004520c4ff2f0808a3e470e55fa0431f4f`
* Token Address: `0x5c87ec90db117509fd654ed7440524323e647394`
* Image URL: `ipfs://bafybeifg57qbtqlhtjlnbqhclaoieykyrffpynmh6pjudyznfiknopmvzq/dark_lounge.jpg`
* [Lexplorer Link](https://lexplorer.io/nfts/0x0f6ef4f04f14af17140d329c769f936776b4c36f-0-0x5c87ec90db117509fd654ed7440524323e647394-0xefa30533c25874d23f31e55be15aad004520c4ff2f0808a3e470e55fa0431f4f-10)

### NFT 02

* nftID: `0x6fee59b2ede7b87639c1a4ff102ceefd0ef0a807053e8779f30c45d3c378c6ad`
* Token Address: `0xc199e10d78cb084affaddb7018e37ff9cf786e3a`
* Image URL: `ipfs://bafybeiezuxh5hknw4p5pvfunswu7adjf33rht3fym2v2s4fp546cjk6qli/stoned_and_confused.png`
* [Lexplorer Link](https://lexplorer.io/nfts/0x23ec509b4a82d465a5a92152a5a43b04442e5f58-0-0xc199e10d78cb084affaddb7018e37ff9cf786e3a-0x6fee59b2ede7b87639c1a4ff102ceefd0ef0a807053e8779f30c45d3c378c6ad-10)

**NOTE**: The images in both NFTs were uploaded as part of CAR files to https://nft.storage. I might be one of the only people on L2 using this method at the moment, but perhaps it is related to the issue?

**Comment by Jye924** [comment] 2022-05-14 08:36
> @Jye924 Thanks for being responsive. I have two that are affected at the moment.
> 
> ### NFT 01
> * nftID: `0xefa30533c25874d23f31e55be15aad004520c4ff2f0808a3e470e55fa0431f4f`
> * Token Address: `0x5c87ec90db117509fd654ed7440524323e647394`
> * Image URL: `ipfs://bafybeifg57qbtqlhtjlnbqhclaoieykyrffpynmh6pjudyznfiknopmvzq/dark_lounge.jpg`
> * [Lexplorer Link](https://lexplorer.io/nfts/0x0f6ef4f04f14af17140d329c769f936776b4c36f-0-0x5c87ec90db117509fd654ed7440524323e647394-0xefa30533c25874d23f31e55be15aad004520c4ff2f0808a3e470e55fa0431f4f-10)
> 
> ### NFT 02
> * nftID: `0x6fee59b2ede7b87639c1a4ff102ceefd0ef0a807053e8779f30c45d3c378c6ad`
> * Token Address: `0xc199e10d78cb084affaddb7018e37ff9cf786e3a`
> * Image URL: `ipfs://bafybeiezuxh5hknw4p5pvfunswu7adjf33rht3fym2v2s4fp546cjk6qli/stoned_and_confused.png`
> * [Lexplorer Link](https://lexplorer.io/nfts/0x23ec509b4a82d465a5a92152a5a43b04442e5f58-0-0xc199e10d78cb084affaddb7018e37ff9cf786e3a-0x6fee59b2ede7b87639c1a4ff102ceefd0ef0a807053e8779f30c45d3c378c6ad-10)
> 
> **NOTE**: The images in both NFTs were uploaded as part of CAR files to https://nft.storage. I might be one of the only people on L2 using this method at the moment, but perhaps it is related to the issue?

Please check your NFTs again.

**Comment by ghost** [comment] 2022-05-14 13:45
@Jye924 I can confirm, both of those are appearing now in my mobile wallet, and I can see them in the web version as well.

I am curious, if you don't mind, what was the issue? Are you manually resolving each NFT, or was it a change somewhere in the infrastructure or API?

**Comment by Jye924** [comment] 2022-05-16 01:55
> @Jye924 I can confirm, both of those are appearing now in my mobile wallet, and I can see them in the web version as well.
> 
> I am curious, if you don't mind, what was the issue? Are you manually resolving each NFT, or was it a change somewhere in the infrastructure or API?

It was a issue in our backend. We will optimize the system.

**Closed as completed** 2022-06-15 13:49 UTC
